---@meta

-- Generated by tools/gen_lua_meta.c from src/api_spec.c.
-- Run `make meta` after changing the spec; do not edit by hand.

---The whole of mshell's configuration and control surface.
---@class mshell
mshell = {}

---Operations on a window. Every one defaults to the focused window.
---@class mshell.window
mshell.window = {}

---Move keyboard focus.
---@class mshell.window.focus
---@overload fun(win: mshell.Window)
mshell.window.focus = {}

---Focus the window to the left.
function mshell.window.focus.left() end

---Focus the window below.
function mshell.window.focus.down() end

---Focus the window above.
function mshell.window.focus.up() end

---Focus the window to the right.
function mshell.window.focus.right() end

---Focus the next window in the stack.
function mshell.window.focus.next() end

---Focus the previous window in the stack.
function mshell.window.focus.prev() end

---Focus the window that had focus before this one.
function mshell.window.focus.last() end

---Move a window: a direction, another desktop, or another monitor.
---@class mshell.window.move
---@overload fun(win?: mshell.Window, opts: mshell.MoveOpts|mshell.Direction)
mshell.window.move = {}

---Swap the window leftward, or move it if it floats.
function mshell.window.move.left() end

---Swap the window downward, or move it if it floats.
function mshell.window.move.down() end

---Swap the window upward, or move it if it floats.
function mshell.window.move.up() end

---Swap the window rightward, or move it if it floats.
function mshell.window.move.right() end

---Move the window to a desktop, creating it if it does not exist.
---@param name string
function mshell.window.move.to_desktop(name) end

---Move the window to another monitor.
---@class mshell.window.move.to_monitor
---@overload fun(monitor: integer|mshell.Step)
mshell.window.move.to_monitor = {}

---Move the window to the next monitor.
function mshell.window.move.to_monitor.next() end

---Move the window to the previous monitor.
function mshell.window.move.to_monitor.prev() end

---Resize a floating window. Tiled windows are sized by the layout.
---@class mshell.window.resize
---@overload fun(win?: mshell.Window, opts: mshell.ResizeOpts|mshell.Direction)
mshell.window.resize = {}

---Grow the floating window leftward.
function mshell.window.resize.left() end

---Grow the floating window downward.
function mshell.window.resize.down() end

---Grow the floating window upward.
function mshell.window.resize.up() end

---Grow the floating window rightward.
function mshell.window.resize.right() end

---Ask the window to close.
function mshell.window.close() end

---Terminate the window's process.
function mshell.window.kill() end

---Minimize the window.
function mshell.window.minimize() end

---Un-minimize a window. With no taskbar this is the only way back.
function mshell.window.restore() end

---Center a floating window on its monitor.
---@param win? mshell.Window
function mshell.window.center(win) end

---Promote a tracked window into the layout.
---@param win? mshell.Window
function mshell.window.promote(win) end

---Whether the window sits outside the layout.
---@class mshell.window.float
---@overload fun(win?: mshell.Window, floating?: boolean)
mshell.window.float = {}

---Float the window, or tile it again.
function mshell.window.float.toggle() end

---Whether the window follows you between desktops.
---@class mshell.window.sticky
mshell.window.sticky = {}

---Show this window on every desktop, or stop.
function mshell.window.sticky.toggle() end

---Whether the window stays in the topmost band.
---@class mshell.window.on_top
mshell.window.on_top = {}

---Keep the window above the others, or stop.
function mshell.window.on_top.toggle() end

---The one window you can summon anywhere and dismiss again.
---@class mshell.window.scratchpad
mshell.window.scratchpad = {}

---Make this window the scratchpad.
function mshell.window.scratchpad.mark() end

---Summon the scratchpad, or dismiss it.
function mshell.window.scratchpad.toggle() end

---Windows asking for attention.
---@class mshell.window.urgent
mshell.window.urgent = {}

---Focus the window that is asking for attention.
function mshell.window.urgent.jump() end

---Fullscreen, in the three flavours the window and the app disagree about.
---@class mshell.window.fullscreen
---@overload fun(win?: mshell.Window, mode?: mshell.FullscreenMode)
mshell.window.fullscreen = {}

---The window covers its monitor.
function mshell.window.fullscreen.window() end

---The app's own fullscreen stays inside the tile.
function mshell.window.fullscreen.content() end

---The app's own fullscreen covers the monitor.
function mshell.window.fullscreen.both() end

---The focused window, or nil when nothing is focused.
---@return mshell.Window?
function mshell.window.get() end

---Every managed window, newest last, optionally filtered.
---@param filter? mshell.WindowFilter
---@return mshell.Window[]
function mshell.window.list(filter) end

---Decide what happens to windows that match.
---Only while the config is loading.
---@param match mshell.RuleMatch
---@param action mshell.RuleAction
---@param opts? mshell.RuleOpts
function mshell.window.rule(match, action, opts) end

---Blanket rules that apply before any window rule.
---@class mshell.window.policy
mshell.window.policy = {}

---Whether anything may float at all.
---@param policy "rules"|"never"
function mshell.window.policy.float(policy) end

---How a window on another desktop is hidden.
---@param policy "cloak"|"hide"
function mshell.window.policy.hide(policy) end

---What an app's own fullscreen is allowed to cover.
---@param policy "contain"|"monitor"
function mshell.window.policy.fullscreen(policy) end

---Where a new floating window lands.
---@param policy "center"|"none"
function mshell.window.policy.placement(policy) end

---Whether windows may minimize at all.
---@param policy "allow"|"never"
function mshell.window.policy.minimize(policy) end

---Smallest size the layout will give a window.
---@param width integer
---@param height integer
function mshell.window.min_size(width, height) end

---Whether owned windows and modals are tiled.
---@param enabled boolean
function mshell.window.manage_owned(enabled) end

---Whether floating windows stay above tiled ones.
---@param enabled boolean
function mshell.window.float_on_top(enabled) end

---Desktops are named, created when you go to one, and destroyed when you leave one empty.
---@class mshell.desktop
mshell.desktop = {}

---Switch to a desktop by name, creating it if it does not exist.
---@class mshell.desktop.focus
---@overload fun(name: string)
mshell.desktop.focus = {}

---Step to the next desktop that exists.
function mshell.desktop.focus.next() end

---Step to the previous desktop that exists.
function mshell.desktop.focus.prev() end

---Go back to the desktop you came from.
function mshell.desktop.focus.last() end

---Show a desktop on a given monitor, or unpin it with nil.
---Only at runtime, from a binding or a callback.
---@param name? string
---@param monitor? integer
---@return boolean
function mshell.desktop.to_monitor(name, monitor) end

---Every desktop that exists, in cycling order.
---@return mshell.Desktop[]
function mshell.desktop.list() end

---The desktop you are on, or nil before the first one exists.
---@return mshell.Desktop?
function mshell.desktop.current() end

---One desktop by name, or nil if no such desktop exists.
---@param name string
---@return mshell.Desktop?
function mshell.desktop.get(name) end

---The windows on a desktop, in layout order.
---@param name? string
---@return mshell.Window[]
function mshell.desktop.windows(name) end

---Settings for desktops whose name matches.
---Only while the config is loading.
---@param pattern string
---@param opts mshell.DesktopRule
function mshell.desktop.rule(pattern, opts) end

---Where a new window is inserted in the stack.
---@param policy mshell.AttachPolicy
function mshell.desktop.attach(policy) end

---Physical displays, as places to put desktops.
---@class mshell.monitor
mshell.monitor = {}

---Move focus to another monitor.
---@class mshell.monitor.focus
---@overload fun(index: integer)
mshell.monitor.focus = {}

---Focus the next monitor.
function mshell.monitor.focus.next() end

---Focus the previous monitor.
function mshell.monitor.focus.prev() end

---Every monitor, in the order Windows enumerates them.
---@return mshell.Monitor[]
function mshell.monitor.list() end

---The focused monitor.
---@return mshell.Monitor?
function mshell.monitor.current() end

---Settings for monitors whose device name or index matches.
---@param pattern string|integer
---@param opts mshell.MonitorRule
function mshell.monitor.rule(pattern, opts) end

---The panel itself: resolution, refresh rate, rotation, HDR.
---@class mshell.display
mshell.display = {}

---High dynamic range, where the panel supports it.
---@class mshell.display.hdr
mshell.display.hdr = {}

---Turn HDR on for the focused monitor, or off.
function mshell.display.hdr.toggle() end

---Refresh rate.
---@class mshell.display.refresh
mshell.display.refresh = {}

---Step to the next refresh rate this panel offers.
---@param step? integer
function mshell.display.refresh.cycle(step) end

---Panel rotation.
---@class mshell.display.rotation
mshell.display.rotation = {}

---Step the focused monitor a quarter turn.
---@param step? integer
function mshell.display.rotation.cycle(step) end

---The landscape/portrait shortcut.
---@class mshell.display.portrait
mshell.display.portrait = {}

---Stand the focused monitor on its side, or lay it back down.
function mshell.display.portrait.toggle() end

---Every mode this panel reports.
---@param device? string
---@return mshell.DisplayMode[]
function mshell.display.modes(device) end

---Apply a mode to a panel.
---@param device? string
---@param mode mshell.DisplayMode
---@return boolean
function mshell.display.set_mode(device, mode) end

---How the windows on a desktop are arranged.
---@class mshell.layout
mshell.layout = {}

---Set the layout of the current desktop.
---@param name mshell.LayoutName
function mshell.layout.set(name) end

---The layout of the current desktop.
---@return mshell.LayoutName
function mshell.layout.get() end

---Step to the next layout.
function mshell.layout.cycle() end

---Master on the left, stack on the right.
function mshell.layout.tiling() end

---One window at a time, filling the screen.
function mshell.layout.monocle() end

---An equal grid.
function mshell.layout.grid() end

---Fibonacci dwindle.
function mshell.layout.spiral() end

---Master in the middle, stack down both sides.
function mshell.layout.centered() end

---Master on top, stack in a row below.
function mshell.layout.bstack() end

---Equal vertical columns.
function mshell.layout.columns() end

---Manual binary splits, placed as you make them.
function mshell.layout.bsp() end

---The master area.
---@class mshell.layout.master
mshell.layout.master = {}

---Make the focused window the master.
function mshell.layout.master.promote() end

---Swap with the master, and back again.
function mshell.layout.master.zoom() end

---How much width the master area takes, 0.2 to 0.9.
---@class mshell.layout.master.ratio
---@overload fun(ratio: number)
mshell.layout.master.ratio = {}

---Give the master area more room.
function mshell.layout.master.ratio.grow() end

---Give the master area less room.
function mshell.layout.master.ratio.shrink() end

---How many windows share the master area.
---@class mshell.layout.master.count
---@overload fun(n: integer)
mshell.layout.master.count = {}

---One more window in the master area.
function mshell.layout.master.count.inc() end

---One fewer window in the master area.
function mshell.layout.master.count.dec() end

---One window's share of its stack.
---@class mshell.layout.cfact
mshell.layout.cfact = {}

---Give the focused window more of its stack.
function mshell.layout.cfact.grow() end

---Give the focused window less of its stack.
function mshell.layout.cfact.shrink() end

---Give the focused window an even share again.
function mshell.layout.cfact.reset() end

---Manual splits, under the bsp layout.
---@class mshell.layout.split
mshell.layout.split = {}

---Put the next window to the right of this one.
function mshell.layout.split.h() end

---Put the next window below this one.
function mshell.layout.split.v() end

---Flip the split holding the focused window.
function mshell.layout.split.rotate() end

---Give the focused side of the split more room.
function mshell.layout.split.grow() end

---Give the focused side of the split less room.
function mshell.layout.split.shrink() end

---Splits that show one child at a time.
---@class mshell.layout.container
mshell.layout.container = {}

---Make this split tabbed, or ordinary again.
function mshell.layout.container.tabbed() end

---Make this split stacked, or ordinary again.
function mshell.layout.container.stacked() end

---Show the container's next child.
function mshell.layout.container.next() end

---Show the container's previous child.
function mshell.layout.container.prev() end

---Gap between windows, and at the screen edge.
---@param inner integer
---@param outer? integer
function mshell.layout.gaps(inner, outer) end

---Drop the gaps when only one window is up.
---@param enabled boolean
function mshell.layout.smart_gaps(enabled) end

---The status bar. There is no taskbar, so this is what tells you where you are.
---@class mshell.bar
mshell.bar = {}

---Configure the bar.
---Only while the config is loading.
---@param opts mshell.BarOpts
function mshell.bar.setup(opts) end

---Hide the bar, or show it.
function mshell.bar.toggle() end

---Switch to the strip across every monitor.
function mshell.bar.top() end

---Switch to the floating panel in the middle.
function mshell.bar.floating() end

---Colours, borders and motion.
---@class mshell.appearance
mshell.appearance = {}

---The focus ring: width and colours.
---@param width integer|mshell.BorderOpts
---@param color? integer
function mshell.appearance.border(width, color) end

---The desktop backdrop. There is no wallpaper.
---@param color integer
function mshell.appearance.background(color) end

---Dim everything but the focused window.
---@param opts boolean|mshell.DimOpts
function mshell.appearance.dim(opts) end

---How long a window takes to move, in milliseconds.
---@param ms integer
function mshell.appearance.animation(ms) end

---Drop the focus ring when there is only one window.
---@param enabled boolean
function mshell.appearance.smart_borders(enabled) end

---Colour the ring of a window asking for attention.
---@param enabled boolean
function mshell.appearance.urgency(enabled) end

---Keybindings and the maps they live in.
---@class mshell.keys
mshell.keys = {}

---Bind a chord to an action or a function.
---Only while the config is loading.
---@param mods string[]
---@param key string
---@param action mshell.Action|fun()|string
---@param opts? mshell.BindOpts
function mshell.keys.bind(mods, key, action, opts) end

---Define a map entered from another binding.
---Only while the config is loading.
---@param name string
---@param bindings table<string, mshell.Binding>
---@param opts? mshell.SubmapOpts
function mshell.keys.submap(name, bindings, opts) end

---The submap a bare leader tap enters.
---Only while the config is loading.
---@param submap string
function mshell.keys.leader(submap) end

---Swallow Alt+Tab, Alt+Escape and Ctrl+Escape.
---@param enabled boolean
function mshell.keys.block_system(enabled) end

---Run a program. Arguments are a separate string, because paths have spaces.
---@class mshell.exec
---@overload fun(cmd: string, args?: string, cwd?: string)
mshell.exec = {}

---Run a program once, when mshell starts.
---Only while the config is loading.
---@param cmd string
---@param args? string
---@param cwd? string
function mshell.exec.startup(cmd, args, cwd) end

---Set an environment variable for everything mshell launches.
---@param name string
---@param value? string
function mshell.exec.setenv(name, value) end

---The session and the machine.
---@class mshell.system
mshell.system = {}

---Lock the session.
function mshell.system.lock() end

---Log out.
function mshell.system.logoff() end

---Restart the machine.
function mshell.system.reboot() end

---Shut down.
function mshell.system.shutdown() end

---Sleep.
function mshell.system.sleep() end

---Hibernate.
function mshell.system.hibernate() end

---Media and volume keys, for keyboards that lack them.
---@class mshell.media
mshell.media = {}

---Play or pause.
function mshell.media.play() end

---Next track.
function mshell.media.next() end

---Previous track.
function mshell.media.prev() end

---Stop.
function mshell.media.stop() end

---System volume.
---@class mshell.media.volume
mshell.media.volume = {}

---Volume up.
function mshell.media.volume.up() end

---Volume down.
function mshell.media.volume.down() end

---Mute, or unmute.
function mshell.media.volume.mute() end

---Capture the screen.
---@class mshell.screenshot
mshell.screenshot = {}

---Capture the whole virtual screen.
function mshell.screenshot.screen() end

---Capture just the focused window.
function mshell.screenshot.window() end

---Show a message. There is no systray, so this is how mshell talks to you.
---@class mshell.notify
---@overload fun(text: string, kind?: mshell.NotifyKind, ms?: integer)
mshell.notify = {}

---Which of its own events mshell announces.
---@param opts mshell.NotifyOpts
function mshell.notify.setup(opts) end

---The run dialog.
---@class mshell.launcher
mshell.launcher = {}

---Open the launcher.
function mshell.launcher.open() end

---The panel listing what the keys in a submap do.
---@class mshell.whichkey
mshell.whichkey = {}

---Configure the which-key panel.
---@param opts mshell.WhichKeyOpts
function mshell.whichkey.setup(opts) end

---Pointer behaviour.
---@class mshell.mouse
mshell.mouse = {}

---Configure the pointer.
---Only while the config is loading.
---@param opts boolean|mshell.MouseOpts
function mshell.mouse.setup(opts) end

---Write a line to the mshell log.
---@class mshell.log
---@overload fun(message: string)
mshell.log = {}

---How much mshell writes to its log.
---@param level mshell.LogLevel
function mshell.log.level(level) end

---Shorthand for the debug log level.
---@param enabled boolean
function mshell.log.verbose(enabled) end

---mshell itself.
---@class mshell.config
mshell.config = {}

---Reload the config file.
function mshell.config.reload() end

---Stop mshell. As the shell, this logs you out.
function mshell.config.quit() end

---Start Explorer alongside mshell and stop swallowing keys.
function mshell.config.panic() end

---Install the latest release.
function mshell.config.update() end

---Restart the privileged helper.
function mshell.config.restart_helper() end

---Reload when the config file is saved.
---@param enabled boolean
function mshell.config.auto_reload(enabled) end

---Check daily for a new release.
---@param enabled boolean
function mshell.config.update_check(enabled) end

---Run a function when something happens.
---Only while the config is loading.
---@param event mshell.Event
---@param handler fun(arg: table)
function mshell.on(event, handler) end

