#include "../src/api_spec.h"

#include <stdio.h>
#include <string.h>

static int has_children(const char *path) {
    size_t n = strlen(path);
    for (const ApiEntry *e = api_spec; e->path; e++)
        if (strncmp(e->path, path, n) == 0 && e->path[n] == '.') return 1;
    return 0;
}

static int is_table_row(const ApiEntry *e) {
    return e->kind == API_NAMESPACE || (e->flags & API_CALLABLE) ||
           has_children(e->path);
}

static int split_params(const char *params, char out[][160], int max) {
    if (!params || !params[0]) return 0;

    int n = 0, depth = 0, len = 0;
    char cur[160];
    for (const char *p = params;; p++) {
        if (*p == '<' || *p == '(') depth++;
        if (*p == '>' || *p == ')') depth--;

        if ((*p == ',' && depth == 0) || *p == '\0') {
            cur[len] = '\0';
            char *s = cur;
            while (*s == ' ') s++;
            if (*s && n < max) snprintf(out[n++], 160, "%s", s);
            len = 0;
            if (*p == '\0') break;
            continue;
        }
        if (len < 158) cur[len++] = *p;
    }
    return n;
}

/* "win: mshell.Window?" is written type-first here and name-first in LuaLS, so
 * the trailing ? moves from the type onto the name. */
static void param_parts(const char *param, char *name, size_t ncap,
                        char *type, size_t tcap) {
    const char *colon = strchr(param, ':');
    if (!colon) {
        snprintf(name, ncap, "%s", param);
        snprintf(type, tcap, "any");
        return;
    }

    size_t nlen = (size_t)(colon - param);
    if (nlen >= ncap) nlen = ncap - 1;
    memcpy(name, param, nlen);
    name[nlen] = '\0';
    while (nlen && name[nlen - 1] == ' ') name[--nlen] = '\0';

    const char *t = colon + 1;
    while (*t == ' ') t++;
    snprintf(type, tcap, "%s", t);

    size_t tlen = strlen(type);
    if (tlen && type[tlen - 1] == '?') {
        type[tlen - 1] = '\0';
        size_t l = strlen(name);
        if (l + 1 < ncap) { name[l] = '?'; name[l + 1] = '\0'; }
    }
}

static void emit_signature(FILE *f, const char *params, const char *returns) {
    char list[12][160];
    int  n = split_params(params, list, 12);

    fputs("fun(", f);
    for (int i = 0; i < n; i++) {
        char name[80], type[160];
        param_parts(list[i], name, sizeof name, type, sizeof type);
        fprintf(f, "%s%s: %s", i ? ", " : "", name, type);
    }
    fputc(')', f);
    if (returns && returns[0]) fprintf(f, ": %s", returns);
}

static void emit_table(FILE *f, const ApiEntry *e) {
    fprintf(f, "---%s\n", e->doc);
    fprintf(f, "---@class mshell.%s\n", e->path);
    if (e->flags & API_CALLABLE) {
        fputs("---@overload ", f);
        emit_signature(f, e->luals_params, e->luals_returns);
        fputc('\n', f);
    }
    fprintf(f, "mshell.%s = {}\n\n", e->path);
}

static void emit_function(FILE *f, const ApiEntry *e) {
    char list[12][160];
    int  n = split_params(e->luals_params, list, 12);

    fprintf(f, "---%s\n", e->doc);
    if (e->flags & API_CONFIG_ONLY)
        fputs("---Only while the config is loading.\n", f);
    if (e->flags & API_RUNTIME_ONLY)
        fputs("---Only at runtime, from a binding or a callback.\n", f);

    char names[12][80];
    for (int i = 0; i < n; i++) {
        char type[160];
        param_parts(list[i], names[i], sizeof names[i], type, sizeof type);
        fprintf(f, "---@param %s %s\n", names[i], type);
    }
    if (e->luals_returns && e->luals_returns[0])
        fprintf(f, "---@return %s\n", e->luals_returns);

    fprintf(f, "function mshell.%s(", e->path);
    for (int i = 0; i < n; i++) {
        char *q = strchr(names[i], '?');
        if (q) *q = '\0';
        fprintf(f, "%s%s", i ? ", " : "", names[i]);
    }
    fputs(") end\n\n", f);
}

int main(int argc, char **argv) {
    const char *out = argc > 1 ? argv[1] : "meta/mshell.lua";
    FILE       *f   = fopen(out, "w");
    if (!f) { fprintf(stderr, "cannot write %s\n", out); return 1; }

    fputs("---@meta\n\n", f);
    fputs("-- Generated by tools/gen_lua_meta.c from src/api_spec.c.\n", f);
    fputs("-- Run `make meta` after changing the spec; do not edit by hand.\n\n", f);
    fputs("---The whole of mshell's configuration and control surface.\n", f);
    fputs("---@class mshell\n", f);
    fputs("mshell = {}\n\n", f);

    for (int i = 0; i < api_spec_count(); i++) {
        const ApiEntry *e = api_spec_at(i);
        if (is_table_row(e)) emit_table(f, e);
        else                 emit_function(f, e);
    }

    fclose(f);
    return 0;
}
