#include "api_spec.h"

#include <string.h>

const ApiEntry api_spec[] = {
    { "window", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Operations on a window. Every one defaults to the focused window.",
      "", NULL },
    { "window.focus", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE | API_TAKES_WINDOW,
      "Move keyboard focus.",
      "win: mshell.Window", NULL },
    { "window.focus.left", "focus_left", ACTION_FOCUS_LEFT,
      API_ACTION, API_REPEATABLE,
      "Focus the window to the left.",
      "", NULL },
    { "window.focus.down", "focus_down", ACTION_FOCUS_DOWN,
      API_ACTION, API_REPEATABLE,
      "Focus the window below.",
      "", NULL },
    { "window.focus.up", "focus_up", ACTION_FOCUS_UP,
      API_ACTION, API_REPEATABLE,
      "Focus the window above.",
      "", NULL },
    { "window.focus.right", "focus_right", ACTION_FOCUS_RIGHT,
      API_ACTION, API_REPEATABLE,
      "Focus the window to the right.",
      "", NULL },
    { "window.focus.next", "focus_next", ACTION_FOCUS_NEXT,
      API_ACTION, API_REPEATABLE,
      "Focus the next window in the stack.",
      "", NULL },
    { "window.focus.prev", "focus_prev", ACTION_FOCUS_PREV,
      API_ACTION, API_REPEATABLE,
      "Focus the previous window in the stack.",
      "", NULL },
    { "window.focus.last", "last_window", ACTION_LAST_WINDOW,
      API_ACTION, 0,
      "Focus the window that had focus before this one.",
      "", NULL },
    { "window.move", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE | API_TAKES_WINDOW,
      "Move a window: a direction, another desktop, or another monitor.",
      "win: mshell.Window?, opts: mshell.MoveOpts|mshell.Direction", NULL },
    { "window.move.left", "move_left", ACTION_MOVE_LEFT,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Swap the window leftward, or move it if it floats.",
      "", NULL },
    { "window.move.down", "move_down", ACTION_MOVE_DOWN,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Swap the window downward, or move it if it floats.",
      "", NULL },
    { "window.move.up", "move_up", ACTION_MOVE_UP,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Swap the window upward, or move it if it floats.",
      "", NULL },
    { "window.move.right", "move_right", ACTION_MOVE_RIGHT,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Swap the window rightward, or move it if it floats.",
      "", NULL },
    { "window.move.to_desktop", "move_to_desktop", ACTION_MOVE_TO_DESKTOP,
      API_ACTION, API_PAYLOAD_STR | API_TAKES_WINDOW,
      "Move the window to a desktop, creating it if it does not exist.",
      "name: string", NULL },
    { "window.move.to_monitor", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE | API_TAKES_WINDOW,
      "Move the window to another monitor.",
      "monitor: integer|mshell.Step", NULL },
    { "window.move.to_monitor.next", "move_to_monitor_next", ACTION_MOVE_TO_MONITOR_NEXT,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Move the window to the next monitor.",
      "", NULL },
    { "window.move.to_monitor.prev", "move_to_monitor_prev", ACTION_MOVE_TO_MONITOR_PREV,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Move the window to the previous monitor.",
      "", NULL },
    { "window.resize", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE | API_TAKES_WINDOW,
      "Resize a floating window. Tiled windows are sized by the layout.",
      "win: mshell.Window?, opts: mshell.ResizeOpts|mshell.Direction", NULL },
    { "window.resize.left", "resize_left", ACTION_RESIZE_LEFT,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Grow the floating window leftward.",
      "", NULL },
    { "window.resize.down", "resize_down", ACTION_RESIZE_DOWN,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Grow the floating window downward.",
      "", NULL },
    { "window.resize.up", "resize_up", ACTION_RESIZE_UP,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Grow the floating window upward.",
      "", NULL },
    { "window.resize.right", "resize_right", ACTION_RESIZE_RIGHT,
      API_ACTION, API_REPEATABLE | API_TAKES_WINDOW,
      "Grow the floating window rightward.",
      "", NULL },
    { "window.close", "close", ACTION_CLOSE,
      API_ACTION, API_TAKES_WINDOW,
      "Ask the window to close.",
      "", NULL },
    { "window.kill", "kill", ACTION_KILL,
      API_ACTION, API_TAKES_WINDOW,
      "Terminate the window's process.",
      "", NULL },
    { "window.minimize", "minimize", ACTION_MINIMIZE,
      API_ACTION, API_TAKES_WINDOW,
      "Minimize the window.",
      "", NULL },
    { "window.restore", "restore", ACTION_RESTORE,
      API_ACTION, API_TAKES_WINDOW,
      "Un-minimize a window. With no taskbar this is the only way back.",
      "", NULL },
    { "window.center", NULL, ACTION_NONE,
      API_METHOD, API_TAKES_WINDOW,
      "Center a floating window on its monitor.",
      "win: mshell.Window?", NULL },
    { "window.promote", NULL, ACTION_NONE,
      API_METHOD, API_TAKES_WINDOW,
      "Promote a tracked window into the layout.",
      "win: mshell.Window?", NULL },
    { "window.float", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE | API_TAKES_WINDOW,
      "Whether the window sits outside the layout.",
      "win: mshell.Window?, floating: boolean?", NULL },
    { "window.float.toggle", "toggle_float", ACTION_TOGGLE_FLOAT,
      API_ACTION, API_TAKES_WINDOW,
      "Float the window, or tile it again.",
      "", NULL },
    { "window.sticky", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Whether the window follows you between desktops.",
      "", NULL },
    { "window.sticky.toggle", "toggle_sticky", ACTION_TOGGLE_STICKY,
      API_ACTION, API_TAKES_WINDOW,
      "Show this window on every desktop, or stop.",
      "", NULL },
    { "window.on_top", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Whether the window stays in the topmost band.",
      "", NULL },
    { "window.on_top.toggle", "toggle_always_on_top", ACTION_TOGGLE_ALWAYS_ON_TOP,
      API_ACTION, API_TAKES_WINDOW,
      "Keep the window above the others, or stop.",
      "", NULL },
    { "window.scratchpad", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The one window you can summon anywhere and dismiss again.",
      "", NULL },
    { "window.scratchpad.mark", "mark_scratchpad", ACTION_MARK_SCRATCHPAD,
      API_ACTION, API_TAKES_WINDOW,
      "Make this window the scratchpad.",
      "", NULL },
    { "window.scratchpad.toggle", "toggle_scratchpad", ACTION_TOGGLE_SCRATCHPAD,
      API_ACTION, 0,
      "Summon the scratchpad, or dismiss it.",
      "", NULL },
    { "window.urgent", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Windows asking for attention.",
      "", NULL },
    { "window.urgent.jump", "jump_urgent", ACTION_JUMP_URGENT,
      API_ACTION, 0,
      "Focus the window that is asking for attention.",
      "", NULL },
    { "window.fullscreen", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE | API_TAKES_WINDOW,
      "Fullscreen, in the three flavours the window and the app disagree about.",
      "win: mshell.Window?, mode: mshell.FullscreenMode?", NULL },
    { "window.fullscreen.window", "fullscreen", ACTION_FULLSCREEN,
      API_ACTION, API_TAKES_WINDOW,
      "The window covers its monitor.",
      "", NULL },
    { "window.fullscreen.content", "fullscreen_content", ACTION_FULLSCREEN_CONTENT,
      API_ACTION, API_TAKES_WINDOW,
      "The app's own fullscreen stays inside the tile.",
      "", NULL },
    { "window.fullscreen.both", "fullscreen_both", ACTION_FULLSCREEN_BOTH,
      API_ACTION, API_TAKES_WINDOW,
      "The app's own fullscreen covers the monitor.",
      "", NULL },
    { "window.get", NULL, ACTION_NONE,
      API_QUERY, 0,
      "The focused window, or nil when nothing is focused.",
      "", "mshell.Window?" },
    { "window.list", NULL, ACTION_NONE,
      API_QUERY, 0,
      "Every managed window, newest last, optionally filtered.",
      "filter: mshell.WindowFilter?", "mshell.Window[]" },
    { "window.rule", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Decide what happens to windows that match.",
      "match: mshell.RuleMatch, action: mshell.RuleAction, opts: mshell.RuleOpts?", NULL },
    { "window.policy", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Blanket rules that apply before any window rule.",
      "", NULL },
    { "window.policy.float", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Whether anything may float at all.",
      "policy: \"rules\"|\"never\"", NULL },
    { "window.policy.hide", NULL, ACTION_NONE,
      API_SETTER, 0,
      "How a window on another desktop is hidden.",
      "policy: \"cloak\"|\"hide\"", NULL },
    { "window.policy.fullscreen", NULL, ACTION_NONE,
      API_SETTER, 0,
      "What an app's own fullscreen is allowed to cover.",
      "policy: \"contain\"|\"monitor\"", NULL },
    { "window.policy.placement", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Where a new floating window lands.",
      "policy: \"center\"|\"none\"", NULL },
    { "window.policy.minimize", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Whether windows may minimize at all.",
      "policy: \"allow\"|\"never\"", NULL },
    { "window.min_size", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Smallest size the layout will give a window.",
      "width: integer, height: integer", NULL },
    { "window.manage_owned", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Whether owned windows and modals are tiled.",
      "enabled: boolean", NULL },
    { "window.float_on_top", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Whether floating windows stay above tiled ones.",
      "enabled: boolean", NULL },
    { "desktop", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Desktops are named, created when you go to one, and destroyed when you leave one empty.",
      "", NULL },
    { "desktop.focus", "switch_desktop", ACTION_SWITCH_DESKTOP,
      API_ACTION, API_PAYLOAD_STR | API_CALLABLE,
      "Switch to a desktop by name, creating it if it does not exist.",
      "name: string", NULL },
    { "desktop.focus.next", "next_desktop", ACTION_NEXT_DESKTOP,
      API_ACTION, API_REPEATABLE,
      "Step to the next desktop that exists.",
      "", NULL },
    { "desktop.focus.prev", "prev_desktop", ACTION_PREV_DESKTOP,
      API_ACTION, API_REPEATABLE,
      "Step to the previous desktop that exists.",
      "", NULL },
    { "desktop.focus.last", "last_desktop", ACTION_LAST_DESKTOP,
      API_ACTION, 0,
      "Go back to the desktop you came from.",
      "", NULL },
    { "desktop.to_monitor", "desktop_to_monitor", ACTION_DESKTOP_TO_MONITOR,
      API_ACTION, API_PAYLOAD_STR | API_RUNTIME_ONLY,
      "Show a desktop on a given monitor, or unpin it with nil.",
      "name: string?, monitor: integer?", "boolean" },
    { "desktop.list", NULL, ACTION_NONE,
      API_QUERY, 0,
      "Every desktop that exists, in cycling order.",
      "", "mshell.Desktop[]" },
    { "desktop.current", NULL, ACTION_NONE,
      API_QUERY, 0,
      "The desktop you are on, or nil before the first one exists.",
      "", "mshell.Desktop?" },
    { "desktop.get", NULL, ACTION_NONE,
      API_QUERY, 0,
      "One desktop by name, or nil if no such desktop exists.",
      "name: string", "mshell.Desktop?" },
    { "desktop.windows", NULL, ACTION_NONE,
      API_QUERY, 0,
      "The windows on a desktop, in layout order.",
      "name: string?", "mshell.Window[]" },
    { "desktop.rule", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Settings for desktops whose name matches.",
      "pattern: string, opts: mshell.DesktopRule", NULL },
    { "desktop.attach", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Where a new window is inserted in the stack.",
      "policy: mshell.AttachPolicy", NULL },
    { "monitor", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Physical displays, as places to put desktops.",
      "", NULL },
    { "monitor.focus", NULL, ACTION_NONE,
      API_NAMESPACE, API_CALLABLE,
      "Move focus to another monitor.",
      "index: integer", NULL },
    { "monitor.focus.next", "focus_monitor_next", ACTION_FOCUS_MONITOR_NEXT,
      API_ACTION, API_REPEATABLE,
      "Focus the next monitor.",
      "", NULL },
    { "monitor.focus.prev", "focus_monitor_prev", ACTION_FOCUS_MONITOR_PREV,
      API_ACTION, API_REPEATABLE,
      "Focus the previous monitor.",
      "", NULL },
    { "monitor.list", NULL, ACTION_NONE,
      API_QUERY, 0,
      "Every monitor, in the order Windows enumerates them.",
      "", "mshell.Monitor[]" },
    { "monitor.current", NULL, ACTION_NONE,
      API_QUERY, 0,
      "The focused monitor.",
      "", "mshell.Monitor?" },
    { "monitor.rule", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Settings for monitors whose device name or index matches.",
      "pattern: string|integer, opts: mshell.MonitorRule", NULL },
    { "display", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The panel itself: resolution, refresh rate, rotation, HDR.",
      "", NULL },
    { "display.hdr", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "High dynamic range, where the panel supports it.",
      "", NULL },
    { "display.hdr.toggle", "toggle_hdr", ACTION_TOGGLE_HDR,
      API_ACTION, 0,
      "Turn HDR on for the focused monitor, or off.",
      "", NULL },
    { "display.refresh", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Refresh rate.",
      "", NULL },
    { "display.refresh.cycle", "cycle_refresh", ACTION_CYCLE_REFRESH,
      API_ACTION, API_PAYLOAD_NUM,
      "Step to the next refresh rate this panel offers.",
      "step: integer?", NULL },
    { "display.rotation", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Panel rotation.",
      "", NULL },
    { "display.rotation.cycle", "cycle_rotation", ACTION_CYCLE_ROTATION,
      API_ACTION, API_PAYLOAD_NUM,
      "Step the focused monitor a quarter turn.",
      "step: integer?", NULL },
    { "display.portrait", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The landscape/portrait shortcut.",
      "", NULL },
    { "display.portrait.toggle", "toggle_portrait", ACTION_TOGGLE_PORTRAIT,
      API_ACTION, 0,
      "Stand the focused monitor on its side, or lay it back down.",
      "", NULL },
    { "display.modes", NULL, ACTION_NONE,
      API_QUERY, 0,
      "Every mode this panel reports.",
      "device: string?", "mshell.DisplayMode[]" },
    { "display.set_mode", NULL, ACTION_NONE,
      API_METHOD, 0,
      "Apply a mode to a panel.",
      "device: string?, mode: mshell.DisplayMode", "boolean" },
    { "layout", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "How the windows on a desktop are arranged.",
      "", NULL },
    { "layout.set", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Set the layout of the current desktop.",
      "name: mshell.LayoutName", NULL },
    { "layout.get", NULL, ACTION_NONE,
      API_QUERY, 0,
      "The layout of the current desktop.",
      "", "mshell.LayoutName" },
    { "layout.cycle", "cycle_layout", ACTION_CYCLE_LAYOUT,
      API_ACTION, API_REPEATABLE,
      "Step to the next layout.",
      "", NULL },
    { "layout.tiling", "layout_tiling", ACTION_LAYOUT_TILING,
      API_ACTION, 0,
      "Master on the left, stack on the right.",
      "", NULL },
    { "layout.monocle", "layout_monocle", ACTION_LAYOUT_MONOCLE,
      API_ACTION, 0,
      "One window at a time, filling the screen.",
      "", NULL },
    { "layout.grid", "layout_grid", ACTION_LAYOUT_GRID,
      API_ACTION, 0,
      "An equal grid.",
      "", NULL },
    { "layout.spiral", "layout_spiral", ACTION_LAYOUT_SPIRAL,
      API_ACTION, 0,
      "Fibonacci dwindle.",
      "", NULL },
    { "layout.centered", "layout_centered", ACTION_LAYOUT_CENTERED,
      API_ACTION, 0,
      "Master in the middle, stack down both sides.",
      "", NULL },
    { "layout.bstack", "layout_bstack", ACTION_LAYOUT_BSTACK,
      API_ACTION, 0,
      "Master on top, stack in a row below.",
      "", NULL },
    { "layout.columns", "layout_columns", ACTION_LAYOUT_COLUMNS,
      API_ACTION, 0,
      "Equal vertical columns.",
      "", NULL },
    { "layout.bsp", "layout_bsp", ACTION_LAYOUT_BSP,
      API_ACTION, 0,
      "Manual binary splits, placed as you make them.",
      "", NULL },
    { "layout.master", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The master area.",
      "", NULL },
    { "layout.master.promote", "promote_master", ACTION_PROMOTE_MASTER,
      API_ACTION, 0,
      "Make the focused window the master.",
      "", NULL },
    { "layout.master.zoom", "zoom", ACTION_ZOOM,
      API_ACTION, 0,
      "Swap with the master, and back again.",
      "", NULL },
    { "layout.master.ratio", NULL, ACTION_NONE,
      API_SETTER, API_CALLABLE,
      "How much width the master area takes, 0.2 to 0.9.",
      "ratio: number", NULL },
    { "layout.master.ratio.grow", "inc_master", ACTION_INC_MASTER,
      API_ACTION, API_REPEATABLE,
      "Give the master area more room.",
      "", NULL },
    { "layout.master.ratio.shrink", "dec_master", ACTION_DEC_MASTER,
      API_ACTION, API_REPEATABLE,
      "Give the master area less room.",
      "", NULL },
    { "layout.master.count", NULL, ACTION_NONE,
      API_SETTER, API_CALLABLE,
      "How many windows share the master area.",
      "n: integer", NULL },
    { "layout.master.count.inc", "inc_nmaster", ACTION_INC_NMASTER,
      API_ACTION, API_REPEATABLE,
      "One more window in the master area.",
      "", NULL },
    { "layout.master.count.dec", "dec_nmaster", ACTION_DEC_NMASTER,
      API_ACTION, API_REPEATABLE,
      "One fewer window in the master area.",
      "", NULL },
    { "layout.cfact", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "One window's share of its stack.",
      "", NULL },
    { "layout.cfact.grow", "inc_cfact", ACTION_INC_CFACT,
      API_ACTION, API_REPEATABLE,
      "Give the focused window more of its stack.",
      "", NULL },
    { "layout.cfact.shrink", "dec_cfact", ACTION_DEC_CFACT,
      API_ACTION, API_REPEATABLE,
      "Give the focused window less of its stack.",
      "", NULL },
    { "layout.cfact.reset", "reset_cfact", ACTION_RESET_CFACT,
      API_ACTION, 0,
      "Give the focused window an even share again.",
      "", NULL },
    { "layout.split", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Manual splits, under the bsp layout.",
      "", NULL },
    { "layout.split.h", "split_h", ACTION_SPLIT_H,
      API_ACTION, 0,
      "Put the next window to the right of this one.",
      "", NULL },
    { "layout.split.v", "split_v", ACTION_SPLIT_V,
      API_ACTION, 0,
      "Put the next window below this one.",
      "", NULL },
    { "layout.split.rotate", "rotate_split", ACTION_ROTATE_SPLIT,
      API_ACTION, 0,
      "Flip the split holding the focused window.",
      "", NULL },
    { "layout.split.grow", "split_grow", ACTION_SPLIT_GROW,
      API_ACTION, 0,
      "Give the focused side of the split more room.",
      "", NULL },
    { "layout.split.shrink", "split_shrink", ACTION_SPLIT_SHRINK,
      API_ACTION, 0,
      "Give the focused side of the split less room.",
      "", NULL },
    { "layout.container", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Splits that show one child at a time.",
      "", NULL },
    { "layout.container.tabbed", "toggle_tabbed", ACTION_TOGGLE_TABBED,
      API_ACTION, 0,
      "Make this split tabbed, or ordinary again.",
      "", NULL },
    { "layout.container.stacked", "toggle_stacked", ACTION_TOGGLE_STACKED,
      API_ACTION, 0,
      "Make this split stacked, or ordinary again.",
      "", NULL },
    { "layout.container.next", "container_next", ACTION_CONTAINER_NEXT,
      API_ACTION, 0,
      "Show the container's next child.",
      "", NULL },
    { "layout.container.prev", "container_prev", ACTION_CONTAINER_PREV,
      API_ACTION, 0,
      "Show the container's previous child.",
      "", NULL },
    { "layout.gaps", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Gap between windows, and at the screen edge.",
      "inner: integer, outer: integer?", NULL },
    { "layout.smart_gaps", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Drop the gaps when only one window is up.",
      "enabled: boolean", NULL },
    { "bar", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The status bar. There is no taskbar, so this is what tells you where you are.",
      "", NULL },
    { "bar.setup", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Configure the bar.",
      "opts: mshell.BarOpts", NULL },
    { "bar.toggle", "toggle_bar", ACTION_TOGGLE_BAR,
      API_ACTION, 0,
      "Hide the bar, or show it.",
      "", NULL },
    { "bar.top", "bar_top", ACTION_BAR_TOP,
      API_ACTION, 0,
      "Switch to the strip across every monitor.",
      "", NULL },
    { "bar.floating", "bar_floating", ACTION_BAR_FLOATING,
      API_ACTION, 0,
      "Switch to the floating panel in the middle.",
      "", NULL },
    { "appearance", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Colours, borders and motion.",
      "", NULL },
    { "appearance.border", NULL, ACTION_NONE,
      API_SETTER, 0,
      "The focus ring: width and colours.",
      "width: integer|mshell.BorderOpts, color: integer?", NULL },
    { "appearance.background", NULL, ACTION_NONE,
      API_SETTER, 0,
      "The desktop backdrop. There is no wallpaper.",
      "color: integer", NULL },
    { "appearance.dim", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Dim everything but the focused window.",
      "opts: boolean|mshell.DimOpts", NULL },
    { "appearance.animation", NULL, ACTION_NONE,
      API_SETTER, 0,
      "How long a window takes to move, in milliseconds.",
      "ms: integer", NULL },
    { "appearance.smart_borders", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Drop the focus ring when there is only one window.",
      "enabled: boolean", NULL },
    { "appearance.urgency", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Colour the ring of a window asking for attention.",
      "enabled: boolean", NULL },
    { "keys", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Keybindings and the maps they live in.",
      "", NULL },
    { "keys.bind", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Bind a chord to an action or a function.",
      "mods: string[], key: string, action: mshell.Action|fun()|string, opts: mshell.BindOpts?", NULL },
    { "keys.submap", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Define a map entered from another binding.",
      "name: string, bindings: table<string, mshell.Binding>, opts: mshell.SubmapOpts?", NULL },
    { "keys.leader", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "The submap a bare leader tap enters.",
      "submap: string", NULL },
    { "keys.block_system", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Swallow Alt+Tab, Alt+Escape and Ctrl+Escape.",
      "enabled: boolean", NULL },
    { "exec", "spawn", ACTION_SPAWN,
      API_ACTION, API_PAYLOAD_STR | API_CALLABLE,
      "Run a program. Arguments are a separate string, because paths have spaces.",
      "cmd: string, args: string?, cwd: string?", NULL },
    { "exec.startup", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Run a program once, when mshell starts.",
      "cmd: string, args: string?, cwd: string?", NULL },
    { "exec.setenv", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Set an environment variable for everything mshell launches.",
      "name: string, value: string?", NULL },
    { "system", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The session and the machine.",
      "", NULL },
    { "system.lock", "lock", ACTION_LOCK,
      API_ACTION, 0,
      "Lock the session.",
      "", NULL },
    { "system.logoff", "logoff", ACTION_LOGOFF,
      API_ACTION, 0,
      "Log out.",
      "", NULL },
    { "system.reboot", "reboot", ACTION_REBOOT,
      API_ACTION, 0,
      "Restart the machine.",
      "", NULL },
    { "system.shutdown", "shutdown", ACTION_SHUTDOWN,
      API_ACTION, 0,
      "Shut down.",
      "", NULL },
    { "system.sleep", "sleep", ACTION_SLEEP,
      API_ACTION, 0,
      "Sleep.",
      "", NULL },
    { "system.hibernate", "hibernate", ACTION_HIBERNATE,
      API_ACTION, 0,
      "Hibernate.",
      "", NULL },
    { "media", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Media and volume keys, for keyboards that lack them.",
      "", NULL },
    { "media.play", "media_play", ACTION_MEDIA_PLAY,
      API_ACTION, 0,
      "Play or pause.",
      "", NULL },
    { "media.next", "media_next", ACTION_MEDIA_NEXT,
      API_ACTION, 0,
      "Next track.",
      "", NULL },
    { "media.prev", "media_prev", ACTION_MEDIA_PREV,
      API_ACTION, 0,
      "Previous track.",
      "", NULL },
    { "media.stop", "media_stop", ACTION_MEDIA_STOP,
      API_ACTION, 0,
      "Stop.",
      "", NULL },
    { "media.volume", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "System volume.",
      "", NULL },
    { "media.volume.up", "volume_up", ACTION_VOLUME_UP,
      API_ACTION, API_REPEATABLE,
      "Volume up.",
      "", NULL },
    { "media.volume.down", "volume_down", ACTION_VOLUME_DOWN,
      API_ACTION, API_REPEATABLE,
      "Volume down.",
      "", NULL },
    { "media.volume.mute", "volume_mute", ACTION_VOLUME_MUTE,
      API_ACTION, 0,
      "Mute, or unmute.",
      "", NULL },
    { "screenshot", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Capture the screen.",
      "", NULL },
    { "screenshot.screen", "screenshot", ACTION_SCREENSHOT,
      API_ACTION, 0,
      "Capture the whole virtual screen.",
      "", NULL },
    { "screenshot.window", "screenshot_window", ACTION_SCREENSHOT_WINDOW,
      API_ACTION, 0,
      "Capture just the focused window.",
      "", NULL },
    { "notify", "notify", ACTION_NOTIFY,
      API_ACTION, API_PAYLOAD_STR | API_CALLABLE,
      "Show a message. There is no systray, so this is how mshell talks to you.",
      "text: string, kind: mshell.NotifyKind?, ms: integer?", NULL },
    { "notify.setup", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Which of its own events mshell announces.",
      "opts: mshell.NotifyOpts", NULL },
    { "launcher", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The run dialog.",
      "", NULL },
    { "launcher.open", "launcher", ACTION_LAUNCHER,
      API_ACTION, 0,
      "Open the launcher.",
      "", NULL },
    { "whichkey", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "The panel listing what the keys in a submap do.",
      "", NULL },
    { "whichkey.setup", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Configure the which-key panel.",
      "opts: mshell.WhichKeyOpts", NULL },
    { "mouse", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "Pointer behaviour.",
      "", NULL },
    { "mouse.setup", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Configure the pointer.",
      "opts: boolean|mshell.MouseOpts", NULL },
    { "log", NULL, ACTION_NONE,
      API_METHOD, API_CALLABLE,
      "Write a line to the mshell log.",
      "message: string", NULL },
    { "log.level", NULL, ACTION_NONE,
      API_SETTER, 0,
      "How much mshell writes to its log.",
      "level: mshell.LogLevel", NULL },
    { "log.verbose", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Shorthand for the debug log level.",
      "enabled: boolean", NULL },
    { "config", NULL, ACTION_NONE,
      API_NAMESPACE, 0,
      "mshell itself.",
      "", NULL },
    { "config.reload", "reload", ACTION_RELOAD,
      API_ACTION, 0,
      "Reload the config file.",
      "", NULL },
    { "config.quit", "quit", ACTION_QUIT,
      API_ACTION, 0,
      "Stop mshell. As the shell, this logs you out.",
      "", NULL },
    { "config.panic", "panic", ACTION_PANIC,
      API_ACTION, 0,
      "Start Explorer alongside mshell and stop swallowing keys.",
      "", NULL },
    { "config.update", "update", ACTION_UPDATE,
      API_ACTION, 0,
      "Install the latest release.",
      "", NULL },
    { "config.restart_helper", "restart_helper", ACTION_RESTART_HELPER,
      API_ACTION, 0,
      "Restart the privileged helper.",
      "", NULL },
    { "config.auto_reload", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Reload when the config file is saved.",
      "enabled: boolean", NULL },
    { "config.update_check", NULL, ACTION_NONE,
      API_SETTER, 0,
      "Check daily for a new release.",
      "enabled: boolean", NULL },
    { "on", NULL, ACTION_NONE,
      API_SETTER, API_CONFIG_ONLY,
      "Run a function when something happens.",
      "event: mshell.Event, handler: fun(arg: table)", NULL },
    { NULL, NULL, ACTION_NONE, API_NAMESPACE, 0, NULL, NULL, NULL }
};

const ApiRemoved api_removed[] = {
    { "bind", "keys.bind" },
    { "submap", "keys.submap" },
    { "set_leader", "keys.leader" },
    { "block_system_keys", "keys.block_system" },
    { "set_gaps", "layout.gaps" },
    { "set_smart_gaps", "layout.smart_gaps" },
    { "set_layout", "layout.set" },
    { "set_master_ratio", "layout.master.ratio" },
    { "set_nmaster", "layout.master.count" },
    { "set_smart_borders", "appearance.smart_borders" },
    { "set_border", "appearance.border" },
    { "set_background", "appearance.background" },
    { "set_dim", "appearance.dim" },
    { "set_animation", "appearance.animation" },
    { "set_urgency", "appearance.urgency" },
    { "set_bar", "bar.setup" },
    { "set_whichkey", "whichkey.setup" },
    { "set_mouse", "mouse.setup" },
    { "set_notify", "notify.setup" },
    { "rule", "window.rule" },
    { "desktop_rule", "desktop.rule" },
    { "monitor_rule", "monitor.rule" },
    { "set_float_policy", "window.policy.float" },
    { "set_hide_policy", "window.policy.hide" },
    { "set_fullscreen_policy", "window.policy.fullscreen" },
    { "set_float_placement", "window.policy.placement" },
    { "set_minimize_policy", "window.policy.minimize" },
    { "set_min_window_size", "window.min_size" },
    { "set_manage_owned", "window.manage_owned" },
    { "set_float_on_top", "window.float_on_top" },
    { "set_attach", "desktop.attach" },
    { "desktop_to_monitor", "desktop.to_monitor" },
    { "spawn", "exec.startup" },
    { "setenv", "exec.setenv" },
    { "set_auto_reload", "config.auto_reload" },
    { "set_update_check", "config.update_check" },
    { "set_verbose", "log.verbose" },
    { "set_log_level", "log.level" },
    { "get_monitors", "monitor.list" },
    { "get_desktops", "desktop.list" },
    { "get_current_desktop", "desktop.current" },
    { "get_focused_window", "window.get" },
    { "set_start_desktop", "desktop.rule" },
    { NULL, NULL }
};

static int ci_equal(const char *a, const char *b) {
    if (!a || !b) return 0;
    for (; *a && *b; a++, b++) {
        char ca = *a, cb = *b;
        if (ca >= 'A' && ca <= 'Z') ca = (char)(ca - 'A' + 'a');
        if (cb >= 'A' && cb <= 'Z') cb = (char)(cb - 'A' + 'a');
        if (ca != cb) return 0;
    }
    return *a == '\0' && *b == '\0';
}

int api_spec_count(void) {
    static int cached = -1;
    if (cached < 0) {
        int n = 0;
        while (api_spec[n].path) n++;
        cached = n;
    }
    return cached;
}

const ApiEntry *api_spec_at(int index) {
    if (index < 0 || index >= api_spec_count()) return NULL;
    return &api_spec[index];
}

const ApiEntry *api_spec_by_path(const char *path) {
    if (!path) return NULL;
    for (const ApiEntry *e = api_spec; e->path; e++)
        if (strcmp(e->path, path) == 0) return e;
    return NULL;
}

const ApiEntry *api_spec_by_legacy(const char *name) {
    if (!name) return NULL;
    for (const ApiEntry *e = api_spec; e->path; e++)
        if (e->legacy_name && ci_equal(e->legacy_name, name)) return e;
    return NULL;
}

const ApiEntry *api_spec_by_action(Action action) {
    if (action == ACTION_NONE) return NULL;
    for (const ApiEntry *e = api_spec; e->path; e++)
        if (e->kind == API_ACTION && e->action == action) return e;
    return NULL;
}

Action api_action_from_name(const char *name) {
    const ApiEntry *e = api_spec_by_legacy(name);
    if (e) return e->action;

    e = api_spec_by_path(name);
    if (e && e->kind == API_ACTION) return e->action;

    return ACTION_NONE;
}

const char *api_action_path(Action action) {
    const ApiEntry *e = api_spec_by_action(action);
    return e ? e->path : NULL;
}

bool api_action_repeatable(Action action) {
    const ApiEntry *e = api_spec_by_action(action);
    return e && (e->flags & API_REPEATABLE) != 0;
}

const char *api_removed_replacement(const char *name) {
    if (!name) return NULL;
    for (const ApiRemoved *r = api_removed; r->removed; r++)
        if (strcmp(r->removed, name) == 0) return r->replacement;
    return NULL;
}

int api_payload_index(const ApiEntry *e, bool first_arg_is_window) {
    if (!e) return 1;
    if ((e->flags & API_TAKES_WINDOW) && first_arg_is_window) return 2;
    return 1;
}
